spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
server:
  port: 8081
  servlet:
    context-path: /api
langchain4j:
  github-models:
    chat-model:
      api-key: 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
      model-name: gpt-4o-mini
      log-requests: true
      log-responses: true
    embedding-model:
      api-key: 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
      model-name: text-embedding-3-small
    streaming-chat-model:
      api-key: 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
      model-name: gpt-4o-mini
  open-ai:
    chat-model:
      log-requests: true
      log-responses: true

bigmodel:
  api-key: 1cadadddaed84763b402d59527765012.tyq9OQfwDwm7gq85
logging:
  level:
    dev.langchain4j: DEBUG

